version: '3.8'

services:
  llm-api-tester:
    build: .
    container_name: llm-api-tester
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      # Mount for development (optional - comment out for production)
      # - .:/app
      # Mount for API keys (optional - for persistent storage)
      - ./api_keys.txt:/app/api_keys.txt:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - llm-network

  # Optional: Add a reverse proxy with nginx for production
  nginx:
    image: nginx:alpine
    container_name: llm-api-tester-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - llm-api-tester
    restart: unless-stopped
    networks:
      - llm-network
    profiles:
      - production

networks:
  llm-network:
    driver: bridge
